### ISSUE TITLE
Luarmor fails to load and issues with unamedESP

### ISSUE THREAD

**Issue by dinowars007** [Riz-ve/Xeno#12]
The title says it, while trying to load a Luarmor script, it ends up failing to load the Luarmor client,  and with unamed esp it behaves very janky / does not run well. On a incognito paste before it got permanently patched, UnamedESP worked perfectly fine with the incognito paste, while on this it behaves very weirdly,/messed up. Would be great if those 2 issues would be resolved. This would overall make the executor a little bit better in my opinion.

Thanks!

**Comment by dinowars007** [comment]
Ah yes also, if u drag a gui and accidentaly touch the windows top bar thing causing ur game to freeze will make the gui permanently stuck to ur mouse cursor and no way to fix it other than rejoin, because it seemsthe mouse is stuck in a position of always clicking for some reason.

**Comment by Riz-ve** [comment]
The drawing library is not the best out there since I have used some random drawing lib that someone gave me. For luarmor could you send me detailed logs of the error you are getting?

**Comment by dinowars007** [comment]
Hello, i checked back and it seems that when it fails it doesn't create any logs, and in the console it is wayyyy too big to even fit in it. i got a screenshot of the console but it only shows the beggining of the error msg, the rest i have to keep making the console larger and larger for the error to continue showing. Anyways here's some screenshot
![luarmor2](https://github.com/user-attachments/assets/c916fd67-c9eb-47f2-93d2-788ba8d7e92b)
![luarmor](https://github.com/user-attachments/assets/f0294473-5945-4b48-9869-7cb00412bc82)

If you want to know what i ran and what game, i played Jailbreak and ran this script: 

loadstring(game:HttpGet("https://cdn.luarmor.net/verified/lunaralite_free.lua"))()

It has a key system, but if u want another script to test (which i did and both sends the same error, you can try this one
loadstring(game:HttpGet('http://scripts.projectauto.xyz/AutoRobV5'))()

Both uses Luarmor.

Thanks!

**Comment by Riz-ve** [comment]
I'm pretty sure this would work now. If you get any errors send them below

**Comment by dinowars007** [comment]
It now says "[AUTH ERROR] Unable to authenticate." and gets kicked for "No HWID Found"

 Thanks
