### ISSUE TITLE
Requested module experienced an error while loading. Function Require.

### ISSUE THREAD

**Issue by dinowars007** [Riz-ve/Xeno#19]
Function shoot
Line 21
and 48 of this script which is:(line 21) 

    localcurrentGun=require(game:GetService("ReplicatedStorage").Game:WaitForChild("ItemSystem"):WaitForChild("ItemSystem")).GetLocalEquipped()
    

and line 48:
    
             shoot()
    
The script is functional on wave lite so it is not the script.
             
Also i'm reporting this as an issue, because this is the first executor that is free that so far executes the script the best.

Would like it if it would be functional. Thanks!

Game in which the script is supposed to run: Jailbreak

(Here's how you are supposed to use the script in case you don't know)
just be as opposite team and get close to a police (blue dots on minimap that will blink if close to you)

Or you can be a police and get near a criminal (not a prisonner)

If the script is correctly executed when close enough to an enemy depending on your team a pistol should either appear if you don't have one or get equipped. and start shooting automatically (intended behaviour that does not happen the shooting part due to the function require error)

And from there if you check the f9 console you should get the error reffering to what i'm reffering to.

If the script doesn't work from what i pasted here then i'm sorry ima upload it as a txt because i tried using github thingy to like copy and paste code directly.

        
    getgenv().toggled = true-- change this to false to stop kill aura. 

    if getgenv().killauraloaded then return end

    local old = require(game:GetService("ReplicatedStorage").Module.RayCast).RayIgnoreNonCollideWithIgnoreList

    local function getNearestEnemy()
    local nearestDistance, nearestEnemy = 1000, nil
    local myTeam = tostring(game:GetService("Players").LocalPlayer.Team)
    for i,v in pairs(game:GetService("Players"):GetPlayers()) do
        local theirTeam = tostring(v.Team)
     if ((myTeam == "Police" and theirTeam == "Criminal") or theirTeam == "Police") and theirTeam ~= myTeam and    v.Character and v.Character:FindFirstChild("HumanoidRootPart") then
      if (v.Character.HumanoidRootPart.Position -    game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.Position).Magnitude < nearestDistance then
          nearestDistance, nearestEnemy = (v.Character.HumanoidRootPart.Position - game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.Position).Magnitude, v
      end
     end
    end
    return nearestEnemy
    end
    local function shoot()
    local currentGun = require(game:GetService("ReplicatedStorage").Game:WaitForChild("ItemSystem"):WaitForChild("ItemSystem")).GetLocalEquipped()
    if not currentGun then return end
           require(game:GetService("ReplicatedStorage").Game:WaitForChild("Item"):WaitForChild("Gun"))._attemptShoot(currentGun)
    end
    getgenv().killauraloaded = true
    while wait(0.5) do
     if getgenv().toggled == false then continue end
     if not game:GetService("Players").LocalPlayer.Character then continue end
     if not game:GetService("Players").LocalPlayer.Character:FindFirstChild("HumanoidRootPart") then continue end

    local nearestEnemy = getNearestEnemy()
    if nearestEnemy then
        require(game:GetService("ReplicatedStorage").Module.RayCast).RayIgnoreNonCollideWithIgnoreList = function(...)
         local arg = {old(...)}
         if (tostring(getfenv(2).script) == "BulletEmitter" or tostring(getfenv(2).script) == "Taser") and nearestEnemy and nearestEnemy.Character and nearestEnemy.Character:FindFirstChild("HumanoidRootPart") and nearestEnemy.Character:FindFirstChild("Humanoid") and (nearestEnemy.Character.HumanoidRootPart.Position - game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.Position).Magnitude < 600 and nearestEnemy.Character.Humanoid.Health > 0 then
            arg[1] = nearestEnemy.Character.HumanoidRootPart
            arg[2] = nearestEnemy.Character.HumanoidRootPart.Position
        end
         return unpack(arg)
     end
     if not game:GetService("Players").LocalPlayer.Folder:FindFirstChild("Pistol") then
         fireclickdetector(workspace.Givers:GetChildren()[17].ClickDetector)
     end
     if game:GetService("Players").LocalPlayer.Folder:FindFirstChild("Pistol") then
         while game:GetService("Players").LocalPlayer.Folder:FindFirstChild("Pistol") and nearestEnemy and nearestEnemy.Character and nearestEnemy.Character:FindFirstChild("HumanoidRootPart") and nearestEnemy.Character:FindFirstChild("Humanoid") and (nearestEnemy.Character.HumanoidRootPart.Position - game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.Position).Magnitude < 600 and nearestEnemy.Character.Humanoid.Health > 0 do
             game:GetService("Players").LocalPlayer.Folder.Pistol.InventoryEquipRemote:FireServer(true)
             wait()
             shoot()
         end
     end
     if game:GetService("Players").LocalPlayer.Folder:FindFirstChild("Pistol") then
         game:GetService("Players").LocalPlayer.Folder.Pistol.InventoryEquipRemote:FireServer(false)
     end
    else
        require(game:GetService("ReplicatedStorage").Module.RayCast).RayIgnoreNonCollideWithIgnoreList = old
     end
    end

**Comment by dinowars007** [comment]
Little update: it seems the script has more issue while trying to use it with xeno, like the pistol not appearing, and the script not looping, did not happen with wave lite

**Comment by Riz-ve** [comment]
the function "require" is unstable and will not work with modules that are requiring other modules
