### ISSUE TITLE
My executor won't open.

### ISSUE THREAD

**Issue by Sproooter** [Riz-ve/Xeno#21]
I have tried everything. From the UWP Roblox, Bloxstrap, and even the web version. I also tried running it as admin but that didn't work either. I have updated my Microsoft Redistributable also. Please help.

**Comment by portal2707070** [comment]
i too

**Comment by portal2707070** [comment]
But it just doesn't appear in the clients.

**Comment by Sproooter** [comment]
> But it just doesn't appear in the clients.
Mine doesn't open at all

**Comment by portal2707070** [comment]
windows defender?

**Comment by Sproooter** [comment]
> windows defender?

yeah its off and still doesn't work, do I need to have the game open?

**Comment by portal2707070** [comment]
I don't know, but it works for me with Roblox closed.

**Comment by Riz-ve** [comment]
https://github.com/Riz-ve/Xeno/issues/23
