### ISSUE TITLE
My executor doesnt open. I tried everything

### ISSUE THREAD

**Issue by AHKSSS3** [Riz-ve/Xeno#23]
I have tried everything. From the UWP Roblox, Bloxstrap, and even the web version. I also tried running it as admin but that didn't work either. I have updated my Microsoft Redistributable also. Please help.

**Comment by AHKSSS3** [comment]
When I open it, the application closes itself. virus programs are also closed

**Comment by Sproooter** [comment]
same here

**Comment by Riz-ve** [comment]
You have not downloaded the dependencies
download .Net SDK and Visual C++ Redistributable

**Comment by Sproooter** [comment]
> You have not downloaded the dependencies download .Net SDK and Visual C++ Redistributable

I just did and restarted my pc, it is still not opening

**Comment by MrRepyhon** [comment]
> > You have not downloaded the dependencies download .Net SDK and Visual C++ Redistributable
> 
> I just did and restarted my pc, it is still not opening

Have you downloaded .NET Framework & .NET Runtime in your computer?

**Comment by Lucas559-noob** [comment]
> > > You have not downloaded the dependencies download .Net SDK and Visual C++ Redistributable
> > 
> > 
> > I just did and restarted my pc, it is still not opening
> 
> Have you downloaded .NET Framework & .NET Runtime in your computer?

yeah and still don't open
