### ISSUE TITLE
No Client Selected

### ISSUE THREAD

**Issue by normal9891** [Riz-ve/Xeno#33]
![image_2024-09-25_163545534](https://github.com/user-attachments/assets/224b0558-7e33-49ad-a05f-968764905d6a)

Whenever i try to execute a script, it says "No Clients are currently selected. Please select atleast one client before trying to execute the script" I use Bloxstrap, I also rejoined mutiple times, reinstalled all the apps, and prolly more which i cannot remember. Help?

**Comment by AHKSSS3** [comment]
Open xeno when you ingame

**Comment by normal9891** [comment]
> Open xeno when you ingame

I am pretty sure that won't solve anything

**Comment by markitos4** [comment]
Here are two fixes:

If u are using the open source compiled into the dll it wont work because it doesn't has offsets updated (rivze didn't published it)

And if u are using release files then idk :p

**Comment by normal9891** [comment]
> If u are using the open source compiled into the dll it wont work because it doesn't has offsets updated (rivze didn't published it)
> 
> And if u are using release files then idk :p

I pressume that The zip is release files, is there a possible way to contact him for support?

**Comment by markitos4** [comment]
yea zip are the release files, idk his discord but u can contact him there

**Comment by PurpleGuyCoyote** [comment]
> Open xeno when you ingame

In roblox home or in roblox game like mm2?

**Comment by normal9891** [comment]
> > Open xeno when you ingame
> 
> In roblox home or in roblox game like mm2?

Prolly he meant in roblox homepage, i tried both a long time ago and it still insist
