### ISSUE TITLE
since when was xeno a trojan

### ISSUE THREAD

**Issue by robloxsadsa** [Riz-ve/Xeno#40]
who made xeno a trojan? im out for you and im closer than you think.

you made a mistake, a very bad mistake.
win32/bearfoos.a!ml

**Comment by robloxsadsa** [comment]
mb chat false positive. anyone know how to make windows 10 defender stop annoying the hell out of me about "threat detected bearfoos"?

**Comment by Sxnpaiwin** [comment]
u just exclude a folder and put xeno in their

**Comment by robloxsadsa** [comment]
it still does it even if i exclude the folder

**Comment by robloxsadsa** [comment]
oh mb i didnt notice you said that. let me try it now.

**Comment by robloxsadsa** [comment]
it works but xeno wont open if i run it in the extracted folder for some reason

**Comment by robloxsadsa** [comment]
nvm thanks man it works.
