### ISSUE TITLE
Execute does nothing 

### ISSUE THREAD

**Issue by Helloimbobhhhh** [Riz-ve/Xeno#41]
When I press execute, nothing happens. I’ve tried multiple different scripts.

**Comment by Burgerrr111** [comment]
open the exe while in the main menu, then press the clients button and if your player shows up, click the checkmark beside the name.

**Comment by PurpleGuyCoyote** [comment]
> When I press execute, nothing happens. I’ve tried multiple different scripts.

Try to execute:
print("hello")
Then check console, if you don't see hello in console, try to reopen BloxTrap and Xeno
