### ISSUE TITLE
Xeno won't execute lots of scirpts

### ISSUE THREAD

**Issue by Gamerboy6415** [Riz-ve/Xeno#42]
So I'm executing a fling script but
![image_2024-09-28_120113140](https://github.com/user-attachments/assets/6cbbdf89-1f62-4d95-9f30-76ef39e8555d)
It shows this, please fix it and make it be able to execute and scripts that's not supported like moonsec or others

**Comment by kiemfp** [comment]
the error is on the script lil bro

**Comment by LuauDev** [comment]
no the issue is with the xeno enviroment code, the userdata is broken, the script works on any other executor like solara but not on xeno, it got an userdata problem i fixed it my self

**Comment by Gamerboy6415** [comment]
Thanks LuauDev! I’ll make sure to remember this

**Comment by cattotaco** [comment]
i hate xeno it doesnt want to execute my skidded script 😡😡😡😡💢💢🤬🤬🤬

**Comment by cattotaco** [comment]
live webcam, hands up skid!!!
