### ISSUE TITLE
bug with lua script

### ISSUE THREAD

**Issue by maximusloltvink** [Riz-ve/Xeno#48]
So, for some reason I made a notification about Inject when I throw it in client.lua attach and it happens, but when I re-login to the Roblox playground, my CoreGUI ui disappears 

local TweenService = game:GetService("TweenService")

local healthgui = Instance.new("ScreenGui")
local healthframe = Instance.new("Frame")
local name = Instance.new("TextLabel")
local info1 = Instance.new("TextLabel")
local line = Instance.new("Frame")

local plr = game.Players.LocalPlayer
local playerhealth = plr.Character.Humanoid.Health

healthgui.Parent = game.CoreGui

local grayColor = Color3.new(0.109804, 0.109804, 0.109804)

healthframe.Parent = healthgui
healthframe.Name = "HealthGui"
healthframe.Position = UDim2.new(1, 0, 0.900, 0)
healthframe.Size = UDim2.new(0, 227, 0, 65)
healthframe.BackgroundColor3 = grayColor
healthframe.BorderColor3 = Color3.new(0.4, 0.4, 0.4)
healthframe.BorderSizePixel = 4

local healthFrameCorner = Instance.new("UICorner")
healthFrameCorner.Parent = healthframe
healthFrameCorner.CornerRadius = UDim.new(0, 12)

name.Parent = healthframe
name.Name = "NameLabel"
name.Size = UDim2.new(0, 87, 0, 30)
name.Position = UDim2.new(0, 0, 0, 0)
name.Text = "Spectra"
name.Font = Enum.Font.Unknown
name.TextScaled = false
name.TextSize = 13
name.BackgroundColor3 = grayColor
name.BorderSizePixel = 3
name.BorderColor3 = Color3.new(0.4, 0.4, 0.4)
name.TextColor3 = Color3.new(1, 1, 1)

local nameLabelCorner = Instance.new("UICorner")
nameLabelCorner.Parent = name
nameLabelCorner.CornerRadius = UDim.new(0, 12)

info1.Parent = healthframe
info1.Name = "InfoLabel"
info1.Size = UDim2.new(0, 150, 0, 25)
info1.Position = UDim2.new(0.05, 0, 0.55, 0)
info1.Text = "Spectra is the best"
info1.Font = Enum.Font.Cartoon
info1.TextSize = 20
info1.BackgroundColor3 = grayColor
info1.BorderSizePixel = 2
info1.BorderColor3 = Color3.new(0.4, 0.4, 0.4)
info1.TextColor3 = Color3.new(1, 1, 1)

local infoLabelCorner = Instance.new("UICorner")
infoLabelCorner.Parent = info1
infoLabelCorner.CornerRadius = UDim.new(0, 12)

line.Parent = healthframe
line.Size = UDim2.new(0, 0, 0, 2)
line.Position = UDim2.new(0.05, 0, 0.45, 0)
line.BackgroundColor3 = Color3.new(1, 1, 1)
line.BackgroundTransparency = 0.5

local function animateAppearance()
    local healthFrameTween = TweenService:Create(healthframe, TweenInfo.new(0.5, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {Position = UDim2.new(0.830, 0, 0.900, 0)})
    healthFrameTween:Play()

    local nameTween = TweenService:Create(name, TweenInfo.new(0.5, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {Position = UDim2.new(0, 0, 0, 0)})
    nameTween:Play()

    local infoTween = TweenService:Create(info1, TweenInfo.new(0.5, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {Position = UDim2.new(0.05, 0, 0.55, 0)})
    infoTween:Play()
end

local function animateDisappearance()
    local healthFrameTween = TweenService:Create(healthframe, TweenInfo.new(0.5, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {Position = UDim2.new(1, 0, 0.900, 0)})
    healthFrameTween:Play()

    local nameTween = TweenService:Create(name, TweenInfo.new(0.5, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {Position = UDim2.new(1, 0, 0, 0)})
    nameTween:Play()

    local infoTween = TweenService:Create(info1, TweenInfo.new(0.5, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {Position = UDim2.new(1, 0, 0.55, 0)})
    infoTween:Play()

    healthFrameTween.Completed:Wait()
    healthgui.Enabled = false
end

local function animateLine()
    local lineTween = TweenService:Create(line, TweenInfo.new(3.5, Enum.EasingStyle.Linear, Enum.EasingDirection.Out), {Size = UDim2.new(0.9, 0, 0, 2)})
    lineTween:Play()
    wait(1.5)
end

animateAppearance()
wait(0)
animateLine()
wait(2.5)
animateDisappearance()

**Comment by LuauDev** [comment]
hmm, maybe send us ur client.lua
