### ISSUE TITLE
when gethiddenproperties will add return the properties values?

### ISSUE THREAD

**Issue by playvoras** [Riz-ve/Xeno#5]

**Comment by Riz-ve** [comment]
Dosent it only return property values?

**Comment by playvoras** [comment]
it only return the properties name not the values too

**Comment by playvoras** [comment]
for i, v in pairs(getproperties(workspace)) do
    print(i, v)
end

**Comment by Riz-ve** [comment]
> it only return the properties/hidden name not the values too

Yes that's exactly what it's doing

**Comment by playvoras** [comment]
so whats the point?
